### ISSUE TITLE
Tooltips are hidden behind color selector

### ISSUE THREAD

**Issue by rm-code** [tavuntu/spriteEditor#1]
A minor issue:
![screenshot 2015-08-16 02 11 12](https://cloud.githubusercontent.com/assets/11627131/9291378/2ac24d20-43bc-11e5-9949-c1923f7b1b3e.png)

**Comment by tavuntu** [comment]
Just fixed that issue last night, it was just the order I was drawing the editor "parts" (not just the components) thanks!
